services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /home/gukjang/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    command:
      - '--storage.tsdb.path=/prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    networks:
      - monitor

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    user: "${UID}:${GID}"
    volumes:
      - ./grafana-volume:/var/lib/grafana
    restart: always
    depends_on:
      - prometheus
    networks:
      - monitor

  node_exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - monitor

volumes:
  grafana-data:
  prometheus-data:

networks:
  monitor:
    driver: bridge