global:
    scrape_interval:     15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 1m
      static_configs:
        - targets: ['172.17.0.1:9090']

    - job_name: 'node'
      static_configs:
        - targets: ['172.17.0.1:9100']